fixed reverse

diff --git a/lab1/main b/lab1/main
--- a/lab1/main
+++ b/lab1/main
@@ -28,7 +28,13 @@ echo "Error: not correct amount of arguments" >&2
 exit 5
 fi;;
 "reverse")
-reverse "$2" "$3";;
+if [[ "$#" -eq 3 ]]
+then
+reverse "$2" "$3"
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "strlen")
 strlen "$2";;
 "_exit")
diff --git a/lab1/reverse b/lab1/reverse
--- a/lab1/reverse
+++ b/lab1/reverse
@@ -2,10 +2,33 @@
 #!/bin/bash
 
 reverse(){
-if ! [[ -f $1 ]] || ! [[ -f $2 ]]
+if ! [[ -f $1 ]] 
 then
-echo "The first or second file does not exist" >&2
-exit -1
+echo "Error: file does not exist" >&2
+exit 7
 fi
+if [[ -e $2 ]]
+then
+if [[ -w $2 && -r $1 ]]
+then 
+if [[ "$1" != "$2" ]]
+then 
 tac $1 > $2
+else
+cat $1 > tmp
+tac tmp > $2
+rm tmp
+fi
+else
+echo "Error: permissin denied" >&2
+exit 9
+fi
+else
+if [[ -r $1 ]]
+then
+tac $1 > $2
+else
+echo "Error: permission denied" >&2
+fi
+fi
 }
