finixed

diff --git a/lab1/main b/lab1/main
--- a/lab1/main
+++ b/lab1/main
@@ -36,13 +36,43 @@ echo "Error: not correct amount of arguments" >&2
 exit 5
 fi;;
 "strlen")
-strlen "$2";;
+if [[ "$#" -eq 2 ]]
+then
+strlen "$2"
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "_exit")
-_exit "$2";;
+if [[ "$#" -eq 2 ]]
+then
+_exit "$2"
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "help")
-help;;
+if [[ "$#" -eq 1 ]]
+then
+help
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "interactive")
-interactive;;
+if [[ "$#" -eq 1 ]]
+then
+interactive
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "log")
-log;;
+if [[ "$#" -eq 1 ]]
+then
+log
+else 
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 esac
diff --git a/lab1/search b/lab1/search
--- a/lab1/search
+++ b/lab1/search
@@ -5,13 +5,13 @@ if [ -d $1 ]
 then 
 if [ -r $1 ]
 then
-grep -IRs $2 $1
+grep -r $2 $1 
 else 
-echo "Error:read permission denied"
+echo "Error:read permission denied" >&2
 exit 7
 fi
 else
-echo "Error:directory does not exist"
+echo "Error:directory does not exist" >&2
 exit 8
 fi
 }
