change search

diff --git a/lab1/main b/lab1/main
--- a/lab1/main
+++ b/lab1/main
@@ -16,11 +16,17 @@ if [[ "$#" -eq 4 ]]
 then 
 calc "$2" "$3" "$4"
 else 
-echo "Only 4 args" >&2
+echo "Error: not correct amount of arguments" >&2
 exit 5
 fi;;
 "search")
-search "$2" "$3";;
+if [[ "$#" -eq 3 ]]
+then
+search "$2" "$3"
+else
+echo "Error: not correct amount of arguments" >&2
+exit 5
+fi;;
 "reverse")
 reverse "$2" "$3";;
 "strlen")
diff --git a/lab1/search b/lab1/search
--- a/lab1/search
+++ b/lab1/search
@@ -1,5 +1,17 @@
 #!/bin/bash
 
 search(){
-grep -r $2 /$1
+if [ -d $1 ]
+then 
+if [ -r $1 ]
+then
+grep -IRs $2 $1
+else 
+echo "Error:read permission denied"
+exit 7
+fi
+else
+echo "Error:directory does not exist"
+exit 8
+fi
 }
